#!/usr/bin/env bash
# vim: ft=bash ts=2 sw=2 sts=2 et :
  
hi() { 
  tput bold; tput setaf 5
  cat<<-'EOF'
                                  .::!!!!!!!:.
.!!!!!:.                        .:!!!!!!!!!!!!
~~~~!!!!!!.                 .:!!!!!!!!!UWWW$$$
    :$$NWX!!:           .:!!!!!!XUWW$$$$$$$$$P
    $$$$$##WX!:      .<!!!!UW$$$$"  $$$$$$$$#
    $$$$$  $$$UX   :!!UW$$$$$$$$$   4$$$$$*
    ^$$$B  $$$$\     $$$$$$$$$$$$   d$$R"
      "*$bd$$$$      '*$$$$$$$$$$$o+#"
           """"          """""""
	EOF
  tput bold; tput setaf 241
  echo "Short cuts:"
  alias | sed 's/alias /  /'
  echo ""
  tput sgr0
}

sinless21="$(dirname $(cd $( dirname "${BASH_SOURCE[0]}" ) && pwd ))"

alias ..='cd ..'
alias ...='cd ../../../'

alias bye="gp; tmux detach"
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias ful="bash $sinless21/ful "
alias gp="git add *;git commit -am save;git push;git status"
alias grep='grep --color=auto'
alias h="history"
alias hello="git pull"
alias ls="ls -G"
alias tmux="tmux -f $sinless21/etc/dottmux "
alias vi="vim -u $sinless21/etc/vimrc "
alias vims="vim +PluginInstall +qall"         
alias pdoc="$HOME/Library/Python/3.8/bin/pdoc"

mkdir -p $sinless21/docs

doc() {
  (cd $sinless21/src
  logo="https://github.com/timm/sinless/raw/main/etc/img/sinless.jpeg"
  foot="Sinless v0.1 (c) 2021 Tim Menzies, unlicense.org. Share and enjoy."
  url="http://github.com/timm/sinless/blob/main/src/sinless"
  pdoc -e sinless=$url -t $sinless21/docs --logo $logo --footer-text "$foot" -o $sinless21/docs sinless.py
  mv $sinless21/docs/sinless.html $sinless21/docs/index.html
  pdoc -e sinless=$url -t $sinless21/docs --logo $logo --footer-text "$foot"                   sinless.py)
}
here() { cd $1; basename `pwd`; }

PROMPT_COMMAND='echo -ne "💋 $(git branch 2>/dev/null | grep '^*' | colrm 1 2):";PS1="$(here ..)/$(here .):\!\e[m ▶ "'
hi
