#!/usr/bin/env bash
# vim: ft=bash ts=2 sw=2 sts=2 et :
  
hi() { 
  tput bold; tput setaf 5
  cat<<-'EOF'
                                  .::!!!!!!!:.
.!!!!!:.                        .:!!!!!!!!!!!!
~~~~!!!!!!.                 .:!!!!!!!!!UWWW$$$
    :$$NWX!!:           .:!!!!!!XUWW$$$$$$$$$P
    $$$$$##WX!:      .<!!!!UW$$$$"  $$$$$$$$#
    $$$$$  $$$UX   :!!UW$$$$$$$$$   4$$$$$*
    ^$$$B  $$$$\     $$$$$$$$$$$$   d$$R"
      "*$bd$$$$      '*$$$$$$$$$$$o+#"
           """"          """""""
	EOF
  tput bold; tput setaf 241
  echo "Short cuts:"
  alias | sed 's/alias /  /'
  echo ""
  tput sgr0
}

sinless21="$(dirname $(cd $( dirname "${BASH_SOURCE[0]}" ) && pwd ))"

alias ..='cd ..'
alias ...='cd ../../../'

alias bye="gp; tmux detach"
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias ful="bash $sinless21/ful "
alias gp="git add *;git commit -am save;git push;git status"
alias grep='grep --color=auto'
alias h="history"
alias hello="git pull"
alias ls="ls -G"
alias tmux="tmux -f $sinless21/etc/dottmux "
alias vi="vim -u $sinless21/etc/vimrc "
alias vims="vim +PluginInstall +qall"         

mkdir -p $sinless21/docs

here() { cd $1; basename `pwd`; }

PROMPT_COMMAND='echo -ne "💋 $(git branch 2>/dev/null | grep '^*' | colrm 1 2):";PS1="$(here ..)/$(here .):\!\e[m ▶ "'
hi
